version: '3.5'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - ./.env
    volumes:
      - ./nextcloud:/var/www/html
    depends_on:
      - nextcloud-db

  nextcloud-db:
    container_name: nextcloud-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env